name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  
jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint


  test:
    runs-on: ubuntu-latest
    needs: lint   # 🔗 runs only if lint passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test


  build:
    runs-on: ubuntu-latest
    needs: test   # 🔗 runs only if test passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Create artifact
        run: |
           SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
           ARTIFACT_NAME="app-${SHORT_SHA}.tar.gz"
           tar -czf $ARTIFACT_NAME node_modules index.js package.json
           echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
           
      - name: Upload artifect
        uses: actions/upload-artifact@v4
        with:
             name: build-artifact
             path: ${{ env.ARTIFACT_NAME }}
          
      - name: Print artifact name
        run: 'echo "✅ Created artifact: $ARTIFACT_NAME"'

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
  
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
  
      - name: Copy artifact to server
        run: |
          scp -i ~/.ssh/id_rsa *.tar.gz \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USERNAME }}/app/
  
      - name: Deploy on server
        run: |
          ssh -i ~/.ssh/id_rsa \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e
            cd /home/$USER/app
            
             echo "📦 Extracting latest artifact"
              LATEST=$(ls -t *.tar.gz | head -1)
              tar -xzf "$LATEST"
    
          # install deps (safe)
          npm install --production
    
          echo "🚀 Resetting PM2 restart count"
          pm2 reset my-node-app || true
      
          echo "🚀 Starting or Restarting app"
          if pm2 list | grep -q "my-node-app"; then
            pm2 restart my-node-app
          else
            pm2 start index.js --name my-node-app
          fi
      
          pm2 save
      
          echo "⏳ Waiting for app to stabilize..."
          sleep 10
      
          echo "🔍 Checking app stability"
      
          RESTARTS=$(pm2 list | grep my-node-app | awk '{print $8}')
          echo "🔁 Restart count: $RESTARTS"
      
          if [ "$RESTARTS" -gt 5 ]; then
            echo "❌ App is unstable! Rolling back..."
      
            PREVIOUS=$(ls -t *.tar.gz | sed -n '2p')
      
            if [ -z "$PREVIOUS" ]; then
              echo "❌ No previous version found!"
              exit 1
            fi
      
            echo "🔄 Rolling back to $PREVIOUS"
            tar -xzf "$PREVIOUS"
      
            pm2 restart my-node-app
      
            echo "✅ Rollback complete"
            exit 1
          else
            echo "✅ Deployment successful and stable"
          fi
          EOF 
             
