# .github/workflows/security.yml
name: Secret Scanning & Auto-Lockdown

on:
  pull_request:
    types: [opened, synchronize]
 
jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to close PR and comment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so we can scan the whole PR

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      #  continue-on-error: true # We handle the failure manually below

      

     
